# Generated by Django 6.1.1 on 2026-09-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите электронную почту', max_length=254, unique=True, verbose_name='Электронная почта')),
                ('full_name', models.CharField(help_text='Иванов Иван Иванович', max_length=300, verbose_name='Введите Ф.И.О')),
                ('comment', models.TextField(blank=True, help_text='Оставьте комментарии', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
            },
        ),
    ]
