# Generated by Django 6.1.1 on 2026-09-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите тему письма', max_length=200, verbose_name='Тема письма')),
                ('text', models.TextField(help_text='Введите сообщение', verbose_name='Сообщение')),
            ],
        ),
    ]
