# Generated by Django 6.1.1 on 2026-09-08 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0002_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='С какого времени доступна рассылка')),
                ('end_time', models.DateTimeField(verbose_name='До какого времени доступна рассылка')),
                (
                    'status',
                    models.CharField(
                        choices=[('end', 'Завершено'), ('create', 'Создано'), ('launched', 'Запущено')], max_length=20
                    ),
                ),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sending.messages')),
                ('recipients', models.ManyToManyField(related_name='getting', to='sending.recipient')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
