# Generated by Django 6.1.1 on 2026-09-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0003_sending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='end_time',
            field=models.TimeField(verbose_name='До какого времени доступна рассылка'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='start_time',
            field=models.TimeField(verbose_name='С какого времени доступна рассылка'),
        ),
    ]
