# Generated by Django 6.1.1 on 2026-09-10 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0004_alter_sending_end_time_alter_sending_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='status',
            field=models.CharField(
                choices=[('Завершено', 'Завершено'), ('Создано', 'Создано'), ('Запущенно', 'Запущено')], max_length=20
            ),
        ),
        migrations.CreateModel(
            name='TryingSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата попытки')),
                (
                    'status',
                    models.CharField(
                        choices=[('Удачно', 'Удачно'), ('Не удачно', 'Не удачно')],
                        max_length=20,
                        verbose_name='Статус попытки',
                    ),
                ),
                ('server_response', models.TextField(verbose_name='Ответ почтового сервера')),
                (
                    'mailing',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='sending',
                        to='sending.sending',
                        verbose_name='Рассылка',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
            },
        ),
    ]
